### ISSUE TITLE
About online training

### ISSUE THREAD

**Issue by houchengbin** [luckiezhou/DynamicTriad#13]
Hi Lekui,

Thanks for your excellent work. 

In https://github.com/luckiezhou/DynamicTriad/blob/fc41df19990ca96751b98e85a2e8faaeb1d57b11/core/__init__.py#L172, it said "online training disabled". I'm wondering what is the definition of online training here, and how to enable it.

Besides, in your paper, did you train the model with one graph per timestep, and then use the previous trained model as well as the graph at next timestep to get the next model (the downstream tasks are then evaluated by the models/embeddings obtained at each timestep), and so on...?
Or did you train the model with all graphs in one go, which gives the "overall" pre-trained model and then use this model to somehow generate embeddings at each timestep, which are then used to evaluate downstream tasks? From https://github.com/luckiezhou/DynamicTriad/blob/fc41df19990ca96751b98e85a2e8faaeb1d57b11/core/__init__.py#L118, It seems that all edges from all dynamic graphs are used together to train the model.

Thanks in advance.

**Comment by ayushgoyaal** [comment]
Hi Lekui,
Can you please confirm this "**It seems that all edges from all dynamic graphs are used together to train the model**."

**Comment by luckiezhou** [comment]
Sorry for the late response.
We do use all the edges during training, which is executed in one run.
As for the 'online' comment, it is a part of our future goal and is not implemented in this project.

**Comment by houchengbin** [comment]
Thanks for your response.
