### ISSUE TITLE
should I use CPU or GPU ?

### ISSUE THREAD

**Issue by BrisksHan** [luckiezhou/DynamicTriad#14]
hi Lukiezhou,

I tried to run a data (65000 vertices, 700000 edges) using GPU (tesla p100 16gb), the program crashed, while there was no problem for small data.  
In your paper, you conducted experiments on larger data, did you use CPU or GPU?

**Comment by BrisksHan** [comment]
hi Lukiezhou,

your work is so interesting.

I read you paper in detail, I get a little confused at function 17 in your paper which is the loss function. It seems that you used the temporal information at time step t+1 to get the embedding result at time step t, is it the case ?

Thanks

**Comment by luckiezhou** [comment]
1. We run our experiments on a single GPU card with 12Gb memory. However, our largest dataset is not as large as yours.
2. Yes, you are correct.

**Comment by BrisksHan** [comment]
thanks!
