### ISSUE TITLE
Seg fault on running demo.sh with -l 1 -s 1

### ISSUE THREAD

**Issue by aravindsankar28** [luckiezhou/DynamicTriad#2]
The error on running the main script with same setting: 

*** stack smashing detected ***: python terminated
Segmentation fault

**Comment by luckiezhou** [comment]
@aravindsankar28 
A bug has been fixed in the latest commit (4fab0bb97e2ac21dbfa4eff62ad7c4ca5f7bb2d8).
I think it should be fine now to run with -l 1 -s 1.
Thanks for reporting this bug, and welcome to respond in this issue if your problem has not been solved.
