### ISSUE TITLE
bash build.sh error

### ISSUE THREAD

**Issue by J-zin** [luckiezhou/DynamicTriad#23]
when i run bash build.sh, i get this error:

[100%] Linking CXX shared library dynamic_triad_cimpl.so
/usr/bin/ld: cannot find -lboost_python-2.7
collect2: error: ld returned 1 exit status
CMakeFiles/dynamic_triad.dir/build.make:83: recipe for target 'dynamic_triad_cimpl.so' failed
make[2]: *** [dynamic_triad_cimpl.so] Error 1
CMakeFiles/Makefile2:75: recipe for target 'CMakeFiles/dynamic_triad.dir/all' failed
make[1]: *** [CMakeFiles/dynamic_triad.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

so, how do i fix it, ths~

**Comment by luckiezhou** [comment]
The error message indicates that the boost python library is not found. The reasons could be 
1. The boost library is installed without the boost python module.
2. The boost python library is installed on a different path that is not found by the compiler.
3. The boost python library has an unexpected name (the default is libboost_python-2.7.so).

In order to solve this problem,
1. Check if the boost python library is installed and locate the library file.
2. Refer to the documentation and issue #5 for instructions on setting the environment variables to make sure the boost python library is detected by the building script.

Please post the full building log if you need further help with the problem.

**Comment by J-zin** [comment]
bash build.sh
![image](https://user-images.githubusercontent.com/30493522/67958890-dd20f600-fc32-11e9-85d1-5a357d6a5c63.png)
python scripts/test.py
![image](https://user-images.githubusercontent.com/30493522/67958907-e6aa5e00-fc32-11e9-862a-e9ad5464c53c.png)

does everything  OK? but I see nothing generated.

**Comment by J-zin** [comment]
bash build.sh
![image](https://user-images.githubusercontent.com/30493522/67997379-e8097400-fc8e-11e9-9218-7217dd9d494d.png)
python script/test.py
![image](https://user-images.githubusercontent.com/30493522/67997612-cb217080-fc8f-11e9-9d0b-b22982485da4.png)

it seems everything is ok, but... when i run bash script/demo.sh, there're something wrong
![image](https://user-images.githubusercontent.com/30493522/67997636-e12f3100-fc8f-11e9-88d2-0495f2f8092f.png)

**Comment by J-zin** [comment]
![image](https://user-images.githubusercontent.com/30493522/67997767-9235cb80-fc90-11e9-98f0-abec06c0a118.png)
is that because my boost version  doesnot match?

**Comment by J-zin** [comment]
Hi,
it seems the code runs successfully...but, there is some problem confuses me.
the input timesteps are0-35, but the output of embedding only has 0-14, there is something wrong???
thanks for your excellent work!!!
![image](https://user-images.githubusercontent.com/30493522/68001018-49d0da80-fc9d-11e9-9447-7a296ed589ad.png)

**Comment by J-zin** [comment]
> Hi,
> it seems the code runs successfully...but, there is some problem confuses me.
> the input timesteps are0-35, but the output of embedding only has 0-14, there is something wrong???
> thanks for your excellent work!!!
> ![image](https://user-images.githubusercontent.com/30493522/68001018-49d0da80-fc9d-11e9-9447-7a296ed589ad.png)

set python . -n 36 will output 36 timesteps embedding...
ths

**Comment by Lushan-112358** [comment]
@J-zin I encountered the same problem you mentioned in first block,and can you teach me how to solve or how you solve? Thank you very very much!

**Comment by J-zin** [comment]
> @J-zin I encountered the same problem you mentioned in first block,and can you teach me how to solve or how you solve? Thank you very very much!
