### ISSUE TITLE
How to use other dataset?

### ISSUE THREAD

**Issue by lowkeygit** [luckiezhou/DynamicTriad#6]
Demo can be run successfully. However, How to run other dataset? Such as DBLP.

1. How did you preprocess the original dataset before you generated the pickle file? Do you mind sharing the approaches or preprocessed code that you used?

2. I noticed that 35 files represents 35 years. However, you mentioned that each time step is a 4-year period. Would you explain more details about how you defined a timestamp?
________________________________
vertices: 51,060 researchers;
edges: 794,552 coauthor relationships.
Each time step is a 4-year period and there is a 2-year interval between the start time of consecutive time steps. 
At time step t, we create an edge between two users weighted by the number of coauthorships between them during that period. 
________________________________

3. Which function in "stdtest" will load these 35 files?

4. The result prints out a embedding vector with a shape of (2000, 48). What's the relationship between them?

btw, your work is great. Hope I have a chance to cite your paper.

Thanks in advance,

**Comment by luckiezhou** [comment]
1. In the "Usage" section, I've described the method to use the program to generate embeddings for general adjacency lists. It is not necessary to generate the pickle file before using the program.
2. In the "Time Model" section I described a convenient function to merge (accumulate the edges in different graph snapshot) several years into one. For example, period=4, stride=2 indicates graphs merged from [0 1 2 3] [3 4 5 6] etc.
3. You are not expected to devote into stdtests.py, but to implement the testing code that suits your own scenario. However, if you insist, you may have a look at the class (and its base classes) in core/dataset/citation.py.
4. It is simply a debugging output indicating that each of the 2000 nodes in the toy data receives its own 48-dim embedding. In fact, the embedding size is #time_steps * 2000 * 48.

**Comment by lowkeygit** [comment]
Thank you.
